# The main entry point of your workflow.
# After configuring, running snakemake -n in a clone of this repository should successfully execute a dry-run of the workflow.

from snakemake.utils import min_version


min_version("6.10.0")


configfile: "config/config.yaml"


pepfile: config["pepfile"]


report: "report/workflow.rst"

  
containerized: "containerization/my_container.sif"


if config["Modus"] == "VaSeqIs":

    include: "rules/common.smk"
    include: "rules/VaSeqIs.smk"

if config["include-data-prep"]:

    include: "rules/preparedata.smk"


if config["database"]["Silva"]:

    include: "rules/get_SILVA_DB.smk"


if config["database"]["Greengenes"]:

    include: "rules/get_Greengenes_DB.smk"


if config["database"]["NCBI"]:

    include: "rules/get_NCBI_DB.smk"


rule all:
    input:
        expand(
            "results/{date}/{date}.tar.gz",
            date=get_date(),
        ),
        expand(
            "logs/{date}_logs.tar.gz",
            date=get_date(),
        ),
    output:
        touch(
            expand(
                "results/archive-indicator/{date}.archived",
                date=get_date(),
            ),
        ),
